# Generated by Django 4.2.25 on 2025-11-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0002_dificuldade_curso_dificuldade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='usuario',
        ),
    ]
