# Generated by Django 5.2.7 on 2025-11-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infohelp', '0003_remove_curso_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='usuario',
        ),
    ]
